#!/bin/bash

clear
echo -e "================================================="
echo -e "#         Premium Auto Script By ANGAHVPS       #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# ANGAHVPS PREMIUM                              #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# ALLAH SWT                                     #"
echo -e "# ANGAHVPS                                      #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "# v2ray malaysia                                #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "================================================="
